#print("talabalar kelishdi")
#print("kompyuterda ishlab boshladik")
#print("ustoz yordam beryapti")
#print("tushunmaganlar sorayapti")
#print("bugun yomgirli havo")
#print("dars tushdan keyin")
#print("guruhda yigitlar kop")
#print("universitetda uqiyman")
#print("dasturiy imjiniring yunalishi")
#print("it claster")
#print("dasturchi bul loyihasi")
#print(6/3)
#print(9/7)
#print(16/7)
#print(12/4)
#print(6//5)
#print(7//4)
#print(8//3)
#print(9//3)
#print(8//5)
print(23//5)
print(33//11)
print(8%3)
print(11%3)
print(20%9)